#### Hello All !! Welome to Python..... Again
    - In the very first session, you were given the bare minimum essentials to get started with playing with data while using pandas.. As a refresher (and to recollect what we covered on that day..)
        - Python as calculator
        - How to create variables
        - Basic datatypes 
        - some containers (list, dictionary)
    - Today lets dig a bit deeper and go a bit structured way to understand Python

#### Agenda and objective 
Let's together break the ice... and tame python
- Creating Variables
- Understanding data types,containers and methods
- loops and conditions
- List comprehensions
- Introduction to numpy, data slicing and dicing


#### Refresher
- Create a variable pi and assign a value 3.14 to it. What is the type of this variable
- Create another variable as api and assign 3.14 to it. Add pi and api
- Create a variable A as hello and B as world. Add A and B. Would it give an error
- Create a list of any 5 elements of your choice

##### Building Blocks of Python
- Data types
    - int, float
    - Boolean- True/False
- Containers
    - string/character str
    - Lists
    - Dictionaries
    - Tuples
    - Sets

###### Lets create boolean variables
- Lets create two variables t and f that have values True and False respectively

In [1]:
t, f = True, False
print(type(t))

<class 'bool'>


##### Lets play with strings and understand methods

In [2]:
A= 'Hello'
print(A)

Hello


In [3]:
print(type(A))

<class 'str'>


- For any container has some methods that can be applied on it such that the content can be manipulated. The available methods can be observed by typing "object." and hit tab.
- Another way is to use the function dir 

In [4]:
dir(A)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',
 'zfill']

- Just a technical note.. the ones that start with double hyphen and ends with double hyphen. The rule is simple do not use it (it is method python calls and not us). More advanced: We can modify them to customize for our needs. But for now the bottomline is "DONOT USE THEM"

##### Activity
- What does method capitalise do
- What are the functionalities of upper lower strip , isalpha, isdecimal, count methods
- *How do we find how many characters are there in the word

Let's tear apart the string
- string="This-is-a-teststring"

In [5]:
string="This-is-a-teststring"
string.split("-")

['This', 'is', 'a', 'teststring']

Observe the output of the string

In [6]:
string1='Pavan'
string1.split()

['Pavan']

In [7]:
string1.split('a')

['P', 'v', 'n']

In [8]:
string1.count('a')

2

In [9]:
string1.find('a')

1

what does 1 signify here ?

Let's look at a new function now.. "Enumerate" and what does it do.

In [10]:
x=enumerate(string1)
list(x)

[(0, 'P'), (1, 'a'), (2, 'v'), (3, 'a'), (4, 'n')]

In [2]:
g ="as df"
list(enumerate(g))

[(0, 'a'), (1, 's'), (2, ' '), (3, 'd'), (4, 'f')]

In [13]:
h = enumerate(g)
type(h)
list(h).index('a')

ValueError: 'a' is not in list

Observe that it is having the index (position) along with the character. This function is useful for us for writin conditions in loops

In [11]:
#Polymorphism
print('Hello'+' Pavan')
print(2+3)
print('2'+'3','2'+' 3')
print(2,'\n',3) #\n is a new line character

Hello Pavan
5
23 2 3
2 
 3


#### ACTIVITY:
1. Create a variable 'firstString' and assign the value 'I am' to it. Create another variable 'secondString' and assign the value 'from INSOFE Batch' to it. 

2. Create an integer variable 'batchNo' and assign the value 40 to it. Concatenate and print such that the result looks this:
 "Hello there: I AM FROM INSOFE BATCH 40!!!"
 
3. Count the number of words in the concatenated sentence. Hint: Words are separated by space

In [12]:
firstString = 'I am'
secondString = 'from INSOFE Batch'
batchNo = 53
print(firstString+' '+secondString+' '+str(batchNo)+'!!!')
c = firstString+' '+secondString+' '+'%d!!!'%(batchNo)
l = c.split(' ')
print(l)

len(l)

I am from INSOFE Batch 53!!!
['I', 'am', 'from', 'INSOFE', 'Batch', '53!!!']


6

#### Since we started with boolean.. lets ask questions that give the response in boolean format.. and extend it to strings
- Logical

In [13]:
print(t|f)
print(t&f)
print(t and f)
print(t or f)
print(not t )

True
False
False
True
False


String Comparision

In [14]:
print('pav' in 'pavan')
print('e' in 'pavan')
print('e' not in 'pavan') #in if used in strings checks for substrings

True
False
True


- Relational operators

In [15]:
print(2==3)
print(2<3)
print(2>3)
print(2 !=3)

False
True
False
True


##### Activity
- Combine both relational and logical operators in a statement such that the output is true and for other statement for which output is false

### Containers
- Lists
    - Accessing List elements
        - Forward indexing
        - Reverse indexing

In [16]:
A=[23,7,0,-11,10,12]

In [17]:
print(A[1]) 

7


Observe that 7 is the second element but the index is 1 since indexing in python starts with 0

In [18]:
print(A[0])

23


In [19]:
print(A[-1],A[-2])

12 10


Observe the reverse indexing, the last element is called with index -1 and one before that by index -2 and so on..

- To get first 4 elements of the list A

In [20]:
print(A[0:3])
print(A[0:4])

[23, 7, 0]
[23, 7, 0, -11]


Observe that the number after the colon that index is excluded and the one before the colon is included

In [21]:
print(A[:4])

[23, 7, 0, -11]


Observe that if nothing is mentioned before the colon then python interprets it as include from first element

In [22]:
print(A[1:])

[7, 0, -11, 10, 12]


Observe that if nothing is mentioned after the colon then python interprets it as include till the last element

- What would be the output of the command given below

- Lets say if we want to change the element -11 to 11 in the list.. how do we do it
    - Find the index of this number and use it 

In [23]:
A[3]=11
print(A)

[23, 7, 0, 11, 10, 12]


Observe that you can change/modify the elements of the list

- Try adding a new element 100 to the list
     - Check if there is a method to add new elements

In [24]:
A.append(100)

- Create a new list with two elements 120 and 380 and then use the methods append and extend on A to add these elements. Observe the output

In [25]:
A.append([100])
print (A)

A.extend([100])
print(A)

[23, 7, 0, 11, 10, 12, 100, [100]]
[23, 7, 0, 11, 10, 12, 100, [100], 100]


Observe and note the difference between append and extend

- Observe the methods in the list
    - What are the functionalities of append, copy, clear, insert, index, pop, remove, sort methods
        - A.method and use shift+tab and read the doc

In [26]:
A=[1,5,0,-11,25,16]
print(A)
A.insert(3,1024)
print(A)
A.pop()
print(A)
A.count(100)
A.reverse()
print(A)


[1, 5, 0, -11, 25, 16]
[1, 5, 0, 1024, -11, 25, 16]
[1, 5, 0, 1024, -11, 25]
[25, -11, 1024, 0, 5, 1]


#### ACTIVITY:
Create a list 'myList' with the following elements in it: 'a', [1, 2, 3] and 'abc' to it. 

Add another element 'batch' to it. Remove [1,2,3] from it. 

In [27]:
myList = ['a', [1,2,3], 'abc']
myList.append('batch')
print(myList)

myList.remove([1,2,3])
print(myList)

['a', [1, 2, 3], 'abc', 'batch']
['a', 'abc', 'batch']


- Let's look at a new function now.. "range" and what does it do.
    - syntax: range(start,stop,step)

In [28]:
print(list(range(5)))
print(list(range(1,5)))
print(list(range(1,5,2)))

[0, 1, 2, 3, 4]
[1, 2, 3, 4]
[1, 3]


#### ACTIVITY:
1. Create a list 'mySecondList' with the following elements in it: 'a', 'b', 23, True. Extract out the last element using reverse indexing. Change the element at index 1 to 'bat'. Print out the modified list

2. Create a list A with values 1 to 4 and and another list B with values 5 to 8. Combine these elements into one list A

3. Add a new element 'Alpha' to the list using list methods

4. What is the difference between extend and insert methods

5. Print the elements in reverse order 

6. How is append different from extend

In [29]:
mySecondList = ['a', 'b', 23, True]
print(mySecondList[-1])

mySecondList[1] = 'bat'
print(mySecondList)

True
['a', 'bat', 23, True]


In [30]:
A = list(range(1,5))
B = list(range(5,9))
A = A+B
print(A)

A.insert(8, 'Alpha')
print(A)

A.insert(0,'Beta')
print(A)

A.reverse()
print(A)

[1, 2, 3, 4, 5, 6, 7, 8]
[1, 2, 3, 4, 5, 6, 7, 8, 'Alpha']
['Beta', 1, 2, 3, 4, 5, 6, 7, 8, 'Alpha']
['Alpha', 8, 7, 6, 5, 4, 3, 2, 1, 'Beta']


### Conditions and Loops

In [32]:
x=int(input("please enter a number: "))

please enter a number: 2


- If condition
    - syntax: 
              if <condition>:
                 what to do
              elif <condition>:
                   what to do
              else:
                 what to do
- indentation is taken care by python... all we need to do is do not break it

In [33]:
if x<2:
    print("Entered number is less than 2")
elif x>2:
    print("Entered number is greater than 2")
else:
    print("Entered number is 2")

Entered number is 2


In [34]:
if x<0:
    print("Entered number is negative")
else:
    print("Entered number is positive")
    

Entered number is positive


- Loops
    -Syntax
         for iterator in list/range:
                 do this

In [35]:
A=[1,11,23,7,117]
for i in A:
    print(i)

1
11
23
7
117


In [36]:
for i in range(len(A)):
    print(i)

0
1
2
3
4


In [37]:
for i in range(len(A)):
    print(A[i])

1
11
23
7
117


Observe the output from the above 3 commands and understand

#### ACTIVITY:
Using a for loop and range() function and relational operator, print out all the odd numbers between 20-30.

The modulo operator in python in %

In [38]:
for i in range(20,31):
    if i%2==1:
        print(i)

21
23
25
27
29


#### ACTIVITY:
Count the number of vowels in the string "Hello Batch 40"
    - List out the vowels.
    - Start a counter with zero
    - If the vowel from list exist in string then increment the counter

In [39]:
vowels = ['a','e','i','o','u']

count=0
for i in "Hello Batch 40":
    if i in vowels:
        print(i)
        count+=1
    
print('\n')
print(count)

e
o
a


3


#### List comprehensions
When programming, frequently we want to transform one type of data into another. 
As a simple example, consider the following code that computes square numbers:

In [40]:
nums = [0, 1, 2, 3, 4]

squares = []
for x in nums:
    if x%2==0:
        squares.append(x ** 2)
print (squares)

[0, 4, 16]


You can make this code simpler using a list comprehension:

In [41]:
nums = [0, 1, 2, 3, 4]
squares = [x ** 2 for x in nums]
print (squares)

[0, 1, 4, 9, 16]


List comprehensions can also contain conditions:

In [42]:
nums = [0, 1, 2, 3, 4]
even_squares = [x ** 2 for x in nums if x % 2 == 0]
print(even_squares)

[0, 4, 16]


#### ACTIVITY: 
Create two variables: 'var1' with values 1-5 and 'var2' with values 10-20 in steps of 2 (i.e., 10,12,14,... etc). Using list comprehensions, create a list of (var1+var2) if (var1+var2) is a multiple of 2.

In [43]:
var1 = list(range(1,6))
var2 = list(range(10,20,2))
print(var1)
print(var2)


var3 = [var1[i]+var2[i] for i in range(len(var1)) if (var1[i]+var2[i])%2==0]
print(var3)

[1, 2, 3, 4, 5]
[10, 12, 14, 16, 18]
[14, 20]


#### Functions

Python functions are defined using the `def` keyword. For example:

In [44]:
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'

for x in [-1, 0, 1]:
    print(sign(x))

negative
zero
positive


We will often define functions to take optional keyword arguments, like this:

In [45]:
def hello(name, loud=False):
    if loud:
        print('HELLO, %s' % name.upper())
    else:
        print('Hello, %s!' % name)

hello('Bob')
hello('Fred', loud=True)

Hello, Bob!
HELLO, FRED


#### Tuples

A tuple is an (immutable) ordered list of values. A tuple is in many ways similar to a list; one of the most important differences is that tuples can be used as keys in dictionaries and as elements of sets, while lists cannot. Here is a trivial example:

In [46]:
A=[('a',1),('b',2),('c',3)]

In [47]:
print("The type of object A is: ",type(A),"\n","The type of first element of object A is: ",type(A[0]),
      "\n","The type of first element of first element of object A is: ",type(A[0][0]),"\n",
      "The type of second element of first element of object A is: ",type(A[0][1]))

The type of object A is:  <class 'list'> 
 The type of first element of object A is:  <class 'tuple'> 
 The type of first element of first element of object A is:  <class 'str'> 
 The type of second element of first element of object A is:  <class 'int'>


Observe the indexing of the values

In [48]:
A[0]=('x',24)

In [49]:
A

[('x', 24), ('b', 2), ('c', 3)]

In [50]:
A[0][0]='x'

TypeError: 'tuple' object does not support item assignment

Observe the the element of the list got changed but the element of the tuple did not

### Dictionaries
A dictionary stores (key, value) pairs.

- Review from previous class

In [51]:
#Create a dictionary with keys 'a','b','c' with corresponding values 1,2 and 3
dict1={'a':1,'b':2,'c':3}

In [52]:
dict1

{'a': 1, 'b': 2, 'c': 3}

In [53]:
for key in dict1:
    print(key,dict1[key])

a 1
b 2
c 3


In [54]:
#Adding a new key value pair
dict1['d']=4
print(dict1)

{'a': 1, 'b': 2, 'c': 3, 'd': 4}


In [55]:
print(dict1.keys())

dict_keys(['a', 'b', 'c', 'd'])


In [56]:
print(dict1.values())

dict_values([1, 2, 3, 4])


In [57]:
dict2={'a':1,'b':2,'a':3}

In [58]:
dict2.keys()

dict_keys(['a', 'b'])

In [59]:
dict2.values()

dict_values([3, 2])

In [60]:
dict3={'a':1,'b':2,'c':1}
print(dict3.keys())
print(dict3.values())

dict_keys(['a', 'b', 'c'])
dict_values([1, 2, 1])


Observe that there can be same values for different keys but keys must be unique in the dictionary

In [61]:
print(list(dict3.keys())[list(dict3.values()).index(2)])

b


### Sets
An unordered collections of unique items

In [62]:
A=[1,1,1,3,4,5,6,7,7,10]
print(A,type(A))
B=set(A)
print(B,type(B))

[1, 1, 1, 3, 4, 5, 6, 7, 7, 10] <class 'list'>
{1, 3, 4, 5, 6, 7, 10} <class 'set'>


In [63]:
#To convert set to a list
B=list(B)
print(B,type(B))

[1, 3, 4, 5, 6, 7, 10] <class 'list'>


### Introduction to Numpy

- Array of values in a grid
- For faster computation
- Optimized storage and retrieval

In [64]:
a=[1,2,3]
b=[4,5,6]
a+b

[1, 2, 3, 4, 5, 6]

In [65]:
x=[]
for i in range(len(a)):
    x.append(a[i]+b[i])
    
print(x)
    

[5, 7, 9]


In [66]:
import numpy as np

- Convenience with mathematical functions

In [67]:
a = np.array([1, 2, 3])  # Create a rank 1 array
print (type(a))
print (a.shape)
print (a[0], a[1], a[2])         

<class 'numpy.ndarray'>
(3,)
1 2 3


In [68]:
b=np.array([4,5,6])
a+b

array([5, 7, 9])

When I wanted to add the corresponding elements, check how convinient arrays are!

In [69]:
print(a**3)

[ 1  8 27]


In [70]:
print(a>2)

[False False  True]


Observe that the operations are vectorized

- Create an array

In [71]:
b = np.array([[1,2,3],[4,5,6]])
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


Observe the output of the command b.shape.. It says that b has 2 rows and 3 columns

### Indexing NumPy Arrays

We now know how to create arrays, but unless we can retrieve results from them, there isn't a lot we can do with NumPy. We can use array indexing to select individual elements, groups of elements, or entire rows and columns. One important thing to keep in mind is that just like Python lists, NumPy is zero-indexed, meaning that the index of the first row is 0, and the index of the first column is 0


In [72]:
b[:,:] #Select everything

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
#Get the first element
b[0,0]

1

In [74]:
#Get the fifth element
b[1,1]

5

In [75]:
# Get the first row
b[0,:]

array([1, 2, 3])

In [76]:
#Get the third column
b[:,2]

array([3, 6])

In [77]:
# Creating a 3 dimensional array
three_dim_array = np.array([[[1,2,3,4], [5,6,7,8], [9,10,11,12]],
              [[1,2,3,4], [5,6,7,8], [9,10,11,12]],
              [[1,2,3,4], [5,6,7,8], [9,10,11,12]]])

In [78]:
three_dim_array

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [79]:
three_dim_array.shape

(3, 3, 4)

In [80]:
#To get from second block, third building first floor i.e element 10
three_dim_array[1,2,1]

10

In [81]:
#To get from first block, second building second floor i.e element 6
three_dim_array[0,1,1]

6

In [82]:
#To get [5,6,7,8] from second block 
three_dim_array[1,1,:]

array([5, 6, 7, 8])

In [83]:
#To get [2,6,10] from third block
three_dim_array[2,:,1]

array([ 2,  6, 10])

In [84]:
#From all blocks second floor [3,7,11] from all
three_dim_array[:,:,2]

array([[ 3,  7, 11],
       [ 3,  7, 11],
       [ 3,  7, 11]])

In [85]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [86]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))

[5 7 9]
[-3 -3 -3]
[ 4 10 18]


In [87]:
#Matrix multiplication
a=np.array([1,2,4])
b=np.array([[3],[4],[5]])
np.matmul(a,b)


array([31])

In [88]:
#Comaprision with R vectorized operations

In [89]:
a = np.array([[1,2], [3, 4], [5, 6]])

In [90]:
#Extract all the values that are greater than 2
a>2

array([[False, False],
       [ True,  True],
       [ True,  True]], dtype=bool)

In [91]:
a[a>2]

array([3, 4, 5, 6])

- Given the above intro, please explore the functions and practice

In [15]:
x=[1,2,2,2,3,4]
b=set(x)

In [16]:
for i in b:
    print(i)

1
2
3
4
