In [3]:
type(list) 

type

In [5]:
a = [1,3,4,6,23]

In [7]:
a[1:4] # before the colon index is included, after the colon the index is excluded

[3, 4, 6]

In [8]:
a[:4] # first 4 elements

[1, 3, 4, 6]

In [9]:
a[3:] # from 4th element to the end

[23]

In [10]:
a[2:9] # though no error ; but when you iterate through the list it throws an index error; hence not a good practice

[4, 6, 23]

In [11]:
a[-1]

23

In [12]:
a[-2]

6

In [15]:
a[-3:] # to get the last 3 elements

[4, 6, 23]

In [21]:
a[len(a)-1]

23

In [22]:
a[:-1] #exclude the last element

[1, 3, 4, 6]

In [23]:
b=[1,2,3,[4,5]]

In [24]:
b

[1, 2, 3, [4, 5]]

In [31]:
b.append('f')

In [27]:
b

[1, 2, 3, [4, 5], 'f']

In [28]:
z=[10,20,30]

In [29]:
b.append(z)

In [32]:
b

[1, 2, 3, [4, 5], 'f', [10, 20, 30], 'f']

In [33]:
b.extend(z) # append inserts as a list and extend merges the other list to main list as last elements

In [34]:
b 

[1, 2, 3, [4, 5], 'f', [10, 20, 30], 'f', 10, 20, 30]

In [41]:
b.pop()

[4, 5]

In [43]:
b.append(z)

In [44]:
b

[1, 2, 3, [10, 20, 30]]

In [48]:
b[3][-3]

10

In [52]:
a.count(10) # count the number occurances of an element in the list

0

In [54]:
# to count the total number of elements in the list

len(a)

5

In [55]:
a.remove(4)

In [56]:
a

[1, 3, 6, 23]

In [58]:
a.insert(2,100) # 100 will be inserted at index position 2 and elements gets left shifted

In [59]:
a

[1, 3, 100, 100, 6, 23]

In [60]:
a.remove(100) # removes the first occurance of the element

In [62]:
a[2] = 'f'

In [63]:
a

[1, 3, 'f', 6, 23]

In [3]:
mylist =['a', [1,2,3], 'abc']

In [6]:
mylist

['a', [1, 2, 3], 'abc', 'batch']

In [5]:
mylist.append('batch')

In [76]:
mylist.remove([1,2,3])

In [77]:
mylist

[[1, 2, 3], 'abc', 'batch']

In [79]:
mylist.insert(0,'h')

In [80]:
mylist

['h', [1, 2, 3], 'abc', 'batch']

In [81]:
mylist.remove([1,2,3])

In [82]:
mylist

['h', 'abc', 'batch']

In [84]:
mySecondList = ['a','b',23,True]

In [85]:
mySecondList[-1]

True

In [86]:
mySecondList[1]='bat' 

In [87]:
mySecondList

['a', 'bat', 23, True]

In [88]:
a=[1,2,3,4]; b=[5,6,7,8] ; c=a+b

In [90]:
c.append('Alpha')

In [91]:
c

[1, 2, 3, 4, 5, 6, 7, 8, 'Alpha']

In [93]:
c.insert(2,'Alpha') 

In [95]:
x=[1,4,6]

In [96]:
c.append(x)

In [97]:
c

[1, 2, 'Alpha', 'Alpha', 3, 4, 5, 6, 7, 8, 'Alpha', [1, 4, 6]]

In [98]:
c.pop()

[1, 4, 6]

In [99]:
c.extend(x)

In [100]:
c

[1, 2, 'Alpha', 'Alpha', 3, 4, 5, 6, 7, 8, 'Alpha', 1, 4, 6]

In [111]:
c.remove(c[-1]) # same as pop

In [117]:
list(range(0,5)) #[0,1,2,3,4]

[0, 1, 2, 3, 4]

In [118]:
list(range(1,10)) # from 1 to 9 

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [1]:
list(range(1,10,2))

[1, 3, 5, 7, 9]

In [2]:
x=input("enter the value:")

enter the value:12


In [4]:
int(x)

12

In [7]:
# same thing can be acheived using below

x=int(input("enter the value:"))

x

enter the value:12


12

In [13]:
if x>0:
    print("positive")
else:
    print("Negative")

positive


In [16]:
comp =100

if x>comp:
    print("x is greater")
elif x<comp:
    print("x is lesser")
else:
    print("x and comp are equals")

x is lesser


In [18]:
a= [12, -1, 'f', 10.93, 'king']

In [20]:
for i in a:
    print(a[i])

IndexError: list index out of range

In [22]:
for i in a:
    print(i)

12
-1
f
10.93
king


In [23]:
for i in range(len(a)):
    print(i)

0
1
2
3
4


In [25]:
range(7) # by default range starts from 0 ; hence it is equivalent to (0,7) ; hence in the above example the i iterates through indices

range(0, 7)

In [26]:
for i in range(len(a)):
    print(a[i])

# as i now is iterating through the indices , a[index] gives the value

12
-1
f
10.93
king


In [31]:
k = [13,21,-7,6]

# check each element is postive or negative

for i in k:
    if(i>0):
        print(i,"--> positive")
    elif(i<0):
        print(i,"--> Negative")
    else:
        print(i, "it is zero")

13 --> positive
21 --> positive
-7 --> Negative
6 --> positive


In [37]:
i=100
while i>=50:
    print(i)
    i -=1

100
99
98
97
96
95
94
93
92
91
90
89
88
87
86
85
84
83
82
81
80
79
78
77
76
75
74
73
72
71
70
69
68
67
66
65
64
63
62
61
60
59
58
57
56
55
54
53
52
51
50


In [43]:
a = list(range(1,51))

In [44]:
a

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50]

In [48]:
b=[]
for i in a:
    if (i % 2 == 0):
        b.append(i)
        

In [53]:
b=[]
for i in range(len(a)):
    if (a[i] % 2 == 0):
        b.insert(i,a[i])

In [54]:
b

[2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50]

In [61]:
# "Hello Batch 53" - count no. of vowels

z = "Hello Batch 53"
nvowels = 0
for i in z:
    if i in 'aeiou':
        nvowels+=1
print(nvowels)

3


In [62]:
def signfunc(x):
    if(x>0):
        print(x, "--> positive")
    else:
        print(x, "--> Negative")

In [67]:
signfunc(11.3)

11.3 --> positive


In [68]:
def addition(a,b):
    return a+b

In [69]:
addition(2,3)

5

In [71]:
c= [i for i in a if i%2 == 0] # list comprehension

In [75]:
d = [i**2 for i in a if i%2 == 0]

In [81]:
x = range(1,50)
b=[]
for i in a:
    if i%2 == 0:
        b.append(1)
    else:
        b.append(0)
print(a,)
print(b,)


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]
[0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]


In [82]:
a=[1,1,1,1,1,1,3,3,3,3,1,1,1,2,2,2,2,0,0,3,3,3]

In [84]:
b=set(a)

In [88]:
[i for i in b]

[0, 1, 2, 3]

In [89]:
for i in b:
    print(i)

0
1
2
3


In [91]:
list(i for i in b)

[0, 1, 2, 3]

In [97]:
c= tuple(i for i in b)

In [101]:
c[2:4]

(2, 3)

In [102]:
c[2]=10

TypeError: 'tuple' object does not support item assignment

In [104]:
x=[('a',1),('b',2),('c',3)]
type(x[0][1])

int

In [105]:
dt = {'a':1, 'b':2, 'c':3}

In [108]:
dt.keys()

dict_keys(['a', 'b', 'c'])


In [109]:
dt.values()

dict_values([1, 2, 3])

In [115]:
for i in dt:
    print(i, dt[i])

a 1
b 2
c 3


In [118]:
[dt[i] for i in dt]

[1, 2, 3]

In [119]:
[i for i in dt]

['a', 'b', 'c']

In [122]:
dt.update({'d':7})

In [123]:
dt

{'a': 1, 'b': 2, 'c': 3, 'd': 7}

In [124]:
dt.popitem()

('d', 7)

In [129]:
dt.pop('b')

KeyError: 'b'

In [131]:
dt['d']=8

In [132]:
dt

{'a': 1, 'c': 3, 'd': 8}

In [133]:
a=[1,2,3]
b=[6,7,7]
c=[]
for i in range(len(a)):
    c.append(a[i]+b[i])
c

[7, 9, 10]

In [134]:
import numpy as np

In [138]:
a=np.array([1,2,3])
b=np.array([4,5,6])
type(a)

a+b



array([5, 7, 9])

In [139]:
np.add(a,b)

array([5, 7, 9])

In [140]:
np.subtract(a,b)

array([-3, -3, -3])

In [141]:
np.multiply(a,b)

array([ 4, 10, 18])

In [142]:
np.divide(a,b)

array([0.25, 0.4 , 0.5 ])

In [144]:
a.shape

(3,)

In [150]:
a=np.array([[1,2],[3,4],[5,6]])

In [147]:
a.sum()

10

In [152]:
a.shape

(3, 2)

In [155]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [158]:
a[1]

array([3, 4])

In [159]:
a[1,:]

array([3, 4])

In [160]:
a[1,]

array([3, 4])

In [161]:
h=np.array([1,2,3,3,4,6])

In [164]:
h>2

array([False, False,  True,  True,  True,  True])

In [169]:
c= (h[h>2])

In [171]:
print(c)

[3 3 4 6]


In [172]:
type(c)

numpy.ndarray

ValueError: setting an array element with a sequence.